### ISSUE TITLE
Marks Are Left On Output

### ISSUE THREAD

**Issue by opticyclic** [godfatherofpolka/ColorizationUsingOptimizationInPython#2]
After running python colorizer.py boy_md.png boy_md.png output.png --view you can see the output.
The marks are still left on the output file.

![boy_bw](https://cloud.githubusercontent.com/assets/1222693/5242685/554b3916-7906-11e4-85fe-98e2ae9d7afd.png)
![boy_md](https://cloud.githubusercontent.com/assets/1222693/5242687/5cfa424c-7906-11e4-8a73-6e982c96e1b8.png)
![output](https://cloud.githubusercontent.com/assets/1222693/5242688/61d1306e-7906-11e4-9097-3470061675a2.png)

**Comment by godfatherofpolka** [comment]
@opticyclic Thanks for the report. The reason for this error seems to be that you used a soft brush to draw the colors on the grey image, thus the color markings were "fading out" on the edge (zoom in closely on the markings and you can see this). Thus, the colorization solver finds a solution where the colors also fade out at the edge of the markings, leaving them visible and making the rest of the colours looked washed out, as this is the constraint given by the markings at their edge. (Interesting side note: The internal parts of a brush stroke are basically ignored, it's only the edges that count, thus, using a 1 px-diameter brush would be enough to mark the grey image, anything wider is just for human convenience.)

I've tried to recreate your markings using a hard/non-fuzzy brush (I'm sorry for the quality, this was done quite quickly), the input image and resulting output are attached. Can you confirm that these files work for you?
![testmarked2](https://cloud.githubusercontent.com/assets/7152306/5243572/645f8ca4-793d-11e4-9491-4862b6c92614.png)
![output](https://cloud.githubusercontent.com/assets/7152306/5243574/6c6868ee-793d-11e4-88c4-b3cab59aee67.png)

I will add a note to the readme specifying how the marking of the images should be done, roughly it's: non-fuzzy, non-transparatent, non-fading, hard edge brushes. (Better yet, I should implement a simple drawing tool directly, so this issue completely disappears).
